Warsztat/Models/ClientsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Warsztat.Models
{
    public class ClientViewModel
    {
        public string Id { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane")]
        [EmailAddress]
        [Display(Name = "Adres e-mail")]
        public string Email { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane")]
        [Display(Name = "Imię")]
        public string Name { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane")]
        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane")]
        [Display(Name = "Miasto")]
        public string City { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane")]
        [Display(Name = "Ulica")]
        public string Street { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane")]
        [Phone]
        [Display(Name = "Telefon")]
        public string Phone { get; set; }


    }
}

Warsztat/Controllers/CarsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Warsztat.DataContexts;
using Warsztat.Models;

namespace Warsztat.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        private IdentityDb db = new IdentityDb();

        public ActionResult History(int? id)
        {
            var currentUserId = User.Identity.GetUserId();
           
            var carAdminReports = from r in db.Reports
                                  where r.CarID == (id)
                                  select r;
            var carReports = from r in db.Reports
                             join c in db.Cars on r.CarID equals c.Id into cr
                             from d in cr
                             where r.CarID == (id) && d.ApplicationUserID ==(currentUserId)
                             select r;
            if (id == null)
            {
                return HttpNotFound();
            }
            

            if (User.IsInRole("Admin"))
            {
                return View(carAdminReports.ToList());
            }
            if (!carReports.Any())
            {
                return View("Error");
            }
            return View(carReports.ToList());
        }

        // GET: Cars
        public ActionResult Index()
        {

            var currentUserId = User.Identity.GetUserId();
            ApplicationUser user = db.Users.FirstOrDefault(x => x.Id == currentUserId);


            var userCars = user.Cars
                .ToList();


            if (User.IsInRole("Admin"))
            {
                return View(db.Cars.ToList());
            }

            return View(userCars);
        }

        // GET: Cars/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            
            var currentUserId = User.Identity.GetUserId();
            ApplicationUser user = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            var userCars = user.Cars.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = userCars.Where(c => c.Id == id).FirstOrDefault();
            if (User.IsInRole("Admin"))
            {
                 car = db.Cars.Find(id);
            }
           
             
           if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        [HttpPost]
        public JsonResult AutoComplete(string prefix)
        {

            var customers = (from c in db.Users
                             where (c.Name.StartsWith(prefix)|| c.LastName.StartsWith(prefix))
                             select new
                             {
                                 label = c.Name + " " + c.LastName,
                                 val = c.Id
                             }).ToList();

            return Json(customers, JsonRequestBehavior.AllowGet);
        }
        
       

    // GET: Cars/Create
    public ActionResult Create()
        {
           
            var currentUserId = User.Identity.GetUserId();
            ApplicationUser user = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            ViewBag.Value= user.Id;
           // ViewBag.Owner = user.UserName;
           
            return View();
        }

        // POST: Cars/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string CustomerName, string CustomerId,[Bind(Include = "Id,Make,Model,Engine,DateOfProduction,PlateNumber,Vin,ApplicationUserID")] Car car)
        {
            ViewBag.Message = "CustomerName: " + CustomerName + " CustomerId: " + CustomerId;
            if (ModelState.IsValid)
            {
                
               
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(car);
        }

        // GET: Cars/Edit/5
        public ActionResult Edit(int? id)
        {
            var currentUserId = User.Identity.GetUserId();
            ApplicationUser user = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            var userCars = user.Cars.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = userCars.Where(c => c.Id == id).FirstOrDefault();
            if (User.IsInRole("Admin"))
            {
                 car = db.Cars.Find(id);
            }
           
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Make,Model,Engine,DateOfProduction,PlateNumber,Vin")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        [Authorize(Roles ="Admin")]
        // GET: Cars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }
        [Authorize(Roles = "Admin")]
        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars.Find(id);
            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Warsztat/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Warsztat.DataContexts;
using Warsztat.Models;
using PagedList;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace Warsztat.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ClientsController : Controller
    {
        private IdentityDb db = new IdentityDb();
        // GET: Clients
        public ActionResult Index(string search, int? page, string currentFilter)
        {
            var client = from d in db.Users
                         select d;

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }
            ViewBag.CurrentFilter = search;


            if (!String.IsNullOrEmpty(search))
            {
                client = client.Where(s => s.LastName.Contains(search)
                                        || s.Name.Contains(search));
            }

            var clients = client.ToList()
                      .Select(u => new ClientViewModel

                      {
                          Id = u.Id,
                          Name = u.Name,
                          LastName = u.LastName,
                          Street = u.Street,
                          City = u.City,
                          Phone = u.Phone,
                          Email = u.Email
                      }).ToList();

          

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(clients.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult Details(string id)
        {
           
            var detail = from d in db.Users
                         where d.Id == id
                         select new
                         {
                             Id = d.Id,
                             Name = d.Name,
                             LastName = d.LastName,
                             Street = d.Street,
                             City = d.City,
                             Phone = d.Phone,
                             Email = d.Email
                         };
            var details = detail.ToList()
                          .Select(d => new ClientViewModel

                          {
                              Id = d.Id,
                              Name = d.Name,
                              LastName = d.LastName,
                              Street = d.Street,
                              City = d.City,
                              Phone = d.Phone,
                              Email = d.Email
                          }).ToList();

            

            if (id == null)
            {
                return HttpNotFound();
            }
            return View(details);
        }


        public ActionResult ClientCars(string id)
        {

            var cars = from c in db.Cars
                       where c.ApplicationUserID == id
                       select c;

            if (id == null)
            {
                return HttpNotFound();
            }
          
            return View(cars.ToList());
        }

        public ActionResult ClientReports(string id ,int? search, int? page, int? currentFilter)
        {
            var reports = from r in db.Reports
                          where r.UserId == id
                          select r;

            if (search != null)
            {
                reports = reports.Where(s => s.Id==(search));
            }
           

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }
            ViewBag.CurrentFilter = search;

          

            if (id == null)
            {
                return HttpNotFound();
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(reports.ToList().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = db.Users.Find(id);


            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,LastName,City, Street, Phone,Email,UserName, SecurityStamp, PasswordHash,EmailConfirmed")]ApplicationUser user )
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public ActionResult PasswordReset(string id)
        {

            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

            var user = userManager.FindById(id);

            string code = userManager.GeneratePasswordResetToken(user.Id);




            return RedirectToAction("ResetPassword", "Account", new { userId = user.Id, code = code });
        }
    }
}

Warsztat/Views/Clients/ClientCars.cshtml
@model IEnumerable<Warsztat.Models.Car>

@{
    ViewBag.Title = "Twoje samochody";
}

<h2 class="mt-5">Przypisane samochody</h2>


<table class="table table-striped mt-4">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Make)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Engine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfProduction)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlateNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUserID)
            </th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            

        </tr>
    </thead>
        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Make)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Engine)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfProduction)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlateNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.UserName)
        </td>
        <td> @Html.ActionLink("Edytuj", "Edit", "Cars", new { id = item.Id }, null)</td>
        <td> @Html.ActionLink("Historia", "History", "Cars", new { id = item.Id }, null)</td>
     
        <td> @Html.ActionLink("Szczegóły", "Details", "Cars", new { id = item.Id }, null)</td>
        <td> @Html.ActionLink("Usuń", "Delete", "Cars", new { id = item.Id }, null) </td>
        
    </tr>
        }

</table>

Warsztat/Views/Clients/ClientReports.cshtml
@model PagedList.IPagedList<Warsztat.Models.Report>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Historia zgłoszeń";
}

<h2 class="mt-5">Historia zgłoszeń użytkownika</h2>

@using (Html.BeginForm())
{
    <form>
        <div class="form-group float-left mt-2">
            <p>
                <b>Wyszukaj po numerze zgłoszenia:</b> @Html.TextBox("search", null, new { @class = "form-input" })
                <input class="btn btn-dark" type="submit" value="Wyszukaj" />
            </p>
        </div>
    </form>

}

<table class="table table-striped mt-4">
    <thead class="thead-dark">
        <tr>
            <th>
                Nr.
            </th>
            <th>
                Typ
            </th>
            <th>
                Status
            </th>
            <th>
                Auto
            </th>
            <th>
                Przebieg
            </th>
            <th>
                Tytuł
            </th>
            <th>
                Opis
            </th>
            <th>
                Data
            </th>
            <th>
                Zgłaszający
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReportType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Car.Make)
            @Html.DisplayFor(modelItem => item.Car.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mileage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReportedBy)
        </td>
        <td>
            @Html.ActionLink("Aktualizuj", "Edit", "Reports", new { id = item.Id }, null)
        </td>
        <td>            
            @Html.ActionLink("Szczegóły", "Details", "Reports", new { id = item.Id }, null)
        </td>
            <td>
            @Html.ActionLink("Usuń", "Delete", "Reports", new { id = item.Id }, null)
        </td>



    </tr>
    }

    @ViewBag.error

</table>
<div class="text-right mt-5">
    Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount
    <div>@Html.PagedListPager(Model, page => Url.Action("ClientReports", new { page }))</div>
</div>

Warsztat/Views/Clients/Details.cshtml
@model IEnumerable<Warsztat.Models.ClientViewModel>


@{
    ViewBag.Title = "Klient";
}

<h2 class="mt-5">Klient</h2>


<table class="table table-striped mt-4">
    <thead class="thead-dark">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th></th>

        </tr>
    </thead>
    @foreach (var item in Model)
    {


        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.ActionLink("Samochody ", "ClientCars", new { id = item.Id })|
                @Html.ActionLink("Zgłoszenia", "ClientReports", new { id = item.Id })
            </td>

        </tr>
        <p class="mb-3">
            @Html.ActionLink("Zmień hasło", "PasswordReset", "Clients", new { id = item.Id }, null)
        </p>

    }
</table>
       
    

Warsztat/Views/Clients/Edit.cshtml
@model Warsztat.Models.ApplicationUser

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 class="mt-5">Edytuj użytkownika</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.PasswordHash)
    @Html.HiddenFor(model => model.SecurityStamp)
    @Html.HiddenFor(model => model.EmailConfirmed)

    <div class="form-row">
        <div class="col mb-3">
            @Html.Label("Imię", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col mb-3">
            @Html.Label("Nazwisko", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col mb-3">
            @Html.Label("Miejscowość", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col mb-3">
            @Html.Label("Ulica", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col mb-3">
            @Html.Label("Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col mb-3">
            @Html.Label("E-mail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Nazwa użytkownika", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 mt-5">
            <input type="submit" value="Zapisz" class="btn btn-dark" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Powrót do listy", "Index")
    </div>

Warsztat/Views/Clients/Index.cshtml
@model PagedList.IPagedList<Warsztat.Models.ClientViewModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Baza klientów";
}

<h2 class="mt-5">Baza klientów</h2>
@Html.ActionLink("Dodaj klienta", "Register", "Account")
@using (Html.BeginForm())
{
    <form>
        <div class="form-group float-left mt-2">
            <p>
                <b>Wyszukaj po imieniu lub nazwisku:</b> @Html.TextBox("search", null, new { @class = "form-input" })
                <input class="btn btn-dark" type="submit" value="Wyszukaj" />
            </p>
        </div>
    </form>

}

<table class="table table-striped mt-4">
    <thead class="thead-dark">
        <tr>
            <th>
                Imię
            </th>
            <th>
                Nazwisko
            </th>
            <th>
                Miejscowość
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.ActionLink("Szczegóły", "Details", new { id = item.Id })
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.Id })
            </td>

        </tr>
    }

</table>

<div class="text-right mt-5">
    Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount
    <div>@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))</div>
</div>